Traceback (most recent call last):
  File "/data/t/t541/jss3_tools/example/SORA/get_hitmap_parallel.py", line 6, in <module>
Traceback (most recent call last):
  File "/data/t/t541/jss3_tools/example/SORA/get_hitmap_parallel.py", line 6, in <module>
Traceback (most recent call last):
  File "/data/t/t541/jss3_tools/example/SORA/get_hitmap_parallel.py", line 6, in <module>
Traceback (most recent call last):
  File "/data/t/t541/jss3_tools/example/SORA/get_hitmap_parallel.py", line 6, in <module>
    from mpi4py import MPI
ImportError: cannot import name 'MPI' from 'mpi4py' (/opt/JX/oss/aarch64/mpi4py/3.1.4/lib/python3.6/site-packages/mpi4py/__init__.py)
    from mpi4py import MPI
ImportError: cannot import name 'MPI' from 'mpi4py' (/opt/JX/oss/aarch64/mpi4py/3.1.4/lib/python3.6/site-packages/mpi4py/__init__.py)
    from mpi4py import MPI
ImportError: cannot import name 'MPI' from 'mpi4py' (/opt/JX/oss/aarch64/mpi4py/3.1.4/lib/python3.6/site-packages/mpi4py/__init__.py)
    from mpi4py import MPI
ImportError: cannot import name 'MPI' from 'mpi4py' (/opt/JX/oss/aarch64/mpi4py/3.1.4/lib/python3.6/site-packages/mpi4py/__init__.py)
